# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdo < Formula
  desc "AI-powered SDLC automation platform"
  homepage "https://github.com/actualyze-ai/kdo"
  version "0.1.0-alpha.1"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/actualyze-ai/kdo/releases/download/v0.1.0-alpha.1/kdo_0.1.0-alpha.1_darwin_all.tar.gz"
    sha256 "8b5f08dc29ac8750efc7ac2b0c4d35779417b8498669a7d9ff37432caebb3f33"

    def install
      bin.install "kdo"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/actualyze-ai/kdo/releases/download/v0.1.0-alpha.1/kdo_0.1.0-alpha.1_linux_amd64.tar.gz"
      sha256 "3a62ef9a0405fb1b2f8b6bc4ae826fc9fcc9b6cc3e3314080546486a0e0bced3"
      def install
        bin.install "kdo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/actualyze-ai/kdo/releases/download/v0.1.0-alpha.1/kdo_0.1.0-alpha.1_linux_arm64.tar.gz"
      sha256 "b39bd6658dd35d73e05f831c38ff9dd6983a4d009b4836490acf7e557d623443"
      def install
        bin.install "kdo"
      end
    end
  end

  # Clean up containers, images, and data before uninstalling binary
  def uninstall
    if File.executable?("#{bin}/kdo")
      system "#{bin}/kdo", "uninstall", "--force"
    end
    super
  end

  def caveats
    <<~EOS
      kdo requires Docker to be running.

      To get started:
        export OPENROUTER_API_KEY="your-api-key"
        kdo install
        kdo start
    EOS
  end

  test do
    system "#{bin}/kdo", "version"
  end
end
