# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdo < Formula
  desc "AI-powered SDLC automation platform"
  homepage "https://github.com/actualyze-ai/kdo"
  version "0.1.0-alpha.4"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/actualyze-ai/kdo/releases/download/v0.1.0-alpha.4/kdo_0.1.0-alpha.4_darwin_all.tar.gz"
    sha256 "2e247137cf021f38e749d6ece0d3aa52a3119f83595408c05719caf9e5e4e400"

    def install
      bin.install "kdo"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/actualyze-ai/kdo/releases/download/v0.1.0-alpha.4/kdo_0.1.0-alpha.4_linux_amd64.tar.gz"
      sha256 "a0405c9f953d68ac5a032b49a141148507a7a4194030564bee07da0dd02b3801"
      def install
        bin.install "kdo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/actualyze-ai/kdo/releases/download/v0.1.0-alpha.4/kdo_0.1.0-alpha.4_linux_arm64.tar.gz"
      sha256 "110145ba2ff9acc449fcb037a573d34d8f605b248c5ca59ed484024e55e7ff30"
      def install
        bin.install "kdo"
      end
    end
  end

  test do
    system "#{bin}/kdo", "version"
  end
end
